#大小写转换
s1='HelloWorld'
s2=s1.upper()
s3=s1.lower()
print(s1,s2,s3)
#字符串的分割
e_mail='zyz@qq.com'
lst=e_mail.split('@')#以@为分割，生成了一个列表
print('邮箱名',lst[0],'邮箱所属',lst[1])
#
print(s1.count('o'))#统计o的次数
#检索
print(s1.find('o'))
print(s1.find('p'))
print(s1.index('o'))#index找不到报错
#判断前缀和后缀
print('demo.py'.endswith('.py'))#判断是否以.py结尾，是否为py文件
print('text.txt'.endswith('.txt'))
print('s1'.startswith('H'))#判断是否以H开头

