lst=[4,56,83,25]
print(lst)
#排序，默认升序
lst.sort()
print(lst)
#降序
lst.sort(reverse=True)
print(lst)
#对字符串的排序,升序先排大写，再排小写
lst2=['banana','apple','orange','Pea']
print(lst2)
lst2.sort()
print(lst2)
#字符串降序排序，先排小写再排大写，就是按首字母的ascii值进行的排序
lst2.sort(reverse=True)
print(lst2)
#忽略大小写进行比较
lst2.sort(key=str.lower)
print(lst2)